CREATE TABLE vouchers (
    id CHAR(36) PRIMARY KEY,
    code VARCHAR(255) NOT NULL,
    discount INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)